server:
  port: 9002

spring:
  application:
    name: SCRIPT-EXECUTION-SERVICE
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL81Dialect
    properties:
      hibernate:
        format_sql: true
        default_schema: cmd
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/synthea_50000p
    username: script_executer
    password: VgYVeu7uY6niCEgM
    hikari:
      schema: cmd
  rabbitmq:
    host: localhost
    username: guest
    password: qyDB72wb%Y6HbjKt
    port: 5672
